In [2]:
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
fd = open("../datasets/List of countries by GDP (nominal) - Wikipedia.htm", "r", encoding = "utf-8")
soup = BeautifulSoup(fd)
fd.close()

In [4]:
all_tables = soup.find_all("table")
print("Total number of tables are {} ".format(len(all_tables)))

Total number of tables are 9

In [49]:
data_table = soup.find("table", {"class": '"wikitable"|}'})
print(type(data_table))
print(data_table)

<class 'bs4.element.Tag'>
<table class='"wikitable"|}' style="margin:auto; width:100%;">
<tbody><tr>
<td style="width:33%; text-align:center;"><b>Per the <a href="https://en.wikipedia.org/wiki/International_Monetary_Fund" title="International Monetary Fund">International Monetary Fund</a> (2017)</b><sup class="reference" id="cite_ref-GDP_IMF_1-2"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-GDP_IMF-1">[1]</a></sup>
</td>
<td style="width:33%; text-align:center;"><b>Per the <a href="https://en.wikipedia.org/wiki/World_Bank" title="World Bank">World Bank</a> (2017)</b><sup class="reference" id="cite_ref-worldbank_20-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-worldbank-20">[20]</a></sup>
</td>
<td style="width:33%; text-align:center;"><b>Per the <a href="https://en.wikipedia.org/wiki/United_Nations" title="United Nations">United Nations</a> (2016)</b><sup class="reference" id="cite_ref-21"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-21">[21]</a></sup><sup class="reference" id="cite_ref-22"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-22">[22]</a></sup>
</td></tr>
<tr valign="top">
<td>
<table class="wikitable sortable jquery-tablesorter" style="margin-left:auto; margin-right:auto; margin-top:0;">
<thead><tr>
<th class="headerSort" data-sort-type="number" role="columnheader button" style="width:2em;" tabindex="0" title="Sort ascending">Rank</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Country</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">GDP<br/>(US$MM)
</th></tr></thead><tbody>
<tr style="font-weight:bold;background:#eaecf0">
<td data-sort-value="-1"> </td>
<td data-sort-value=""><span class="flagicon" style="padding-left:25px;"> </span><i><a href="https://en.wikipedia.org/wiki/Gross_world_product" title="Gross world product">World</a></i><sup class="reference" id="cite_ref-IMF_Groups_19-1"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-IMF_Groups-19">[19]</a></sup></td>
<td align="right">79,865,481
</td></tr>
<tr>
<td align="right">1</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_States" title="United States">United States</a></td>
<td align="right">19,390,600
</td></tr>
<tr>
<td align="right">2</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_People's_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/China" title="China">China</a><sup class="reference" id="cite_ref-China-THM_23-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-China-THM-23">[n 1]</a></sup></td>
<td align="right">12,014,610
</td></tr>
<tr>
<td align="right">3</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/35px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/45px-Flag_of_Japan.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Japan" title="Japan">Japan</a></td>
<td align="right">4,872,135
</td></tr>
<tr>
<td align="right">4</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/35px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/46px-Flag_of_Germany.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Germany" title="Germany">Germany</a></td>
<td align="right">3,684,816
</td></tr>
<tr>
<td align="right">5</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_Kingdom" title="United Kingdom">United Kingdom</a></td>
<td align="right">2,624,529
</td></tr>
<tr>
<td align="right">6</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="900" data-file-width="1350" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/India" title="India">India</a></td>
<td align="right">2,611,012
</td></tr>
<tr>
<td align="right">7</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_France.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/35px-Flag_of_France.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/France" title="France">France</a></td>
<td align="right">2,583,560
</td></tr>
<tr>
<td align="right">8</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="504" data-file-width="720" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/22px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/33px-Flag_of_Brazil.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/43px-Flag_of_Brazil.svg.png 2x" width="22"/> </span><a href="https://en.wikipedia.org/wiki/Brazil" title="Brazil">Brazil</a></td>
<td align="right">2,054,969
</td></tr>
<tr>
<td align="right">9</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1500" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Italy.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/35px-Flag_of_Italy.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/45px-Flag_of_Italy.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Italy" title="Italy">Italy</a></td>
<td align="right">1,937,894
</td></tr>
<tr>
<td align="right">10</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="1000" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/Flag_of_Canada.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/35px-Flag_of_Canada.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/46px-Flag_of_Canada.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Canada" title="Canada">Canada</a></td>
<td align="right">1,652,412
</td></tr>
<tr>
<td align="right">11</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/South_Korea" title="South Korea">South Korea</a></td>
<td align="right">1,538,030
</td></tr>
<tr>
<td align="right">12</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/35px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/45px-Flag_of_Russia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Russia" title="Russia">Russia</a><sup class="reference" id="cite_ref-Russia_24-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-Russia-24">[n 2]</a></sup></td>
<td align="right">1,527,469
</td></tr>
<tr>
<td align="right">13</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="640" data-file-width="1280" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Australia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/35px-Flag_of_Australia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/46px-Flag_of_Australia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Australia" title="Australia">Australia</a></td>
<td align="right">1,379,548
</td></tr>
<tr>
<td align="right">14</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Spain.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/35px-Flag_of_Spain.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/45px-Flag_of_Spain.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Spain" title="Spain">Spain</a></td>
<td align="right">1,313,951
</td></tr>
<tr>
<td align="right">15</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="480" data-file-width="840" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/35px-Flag_of_Mexico.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/46px-Flag_of_Mexico.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Mexico" title="Mexico">Mexico</a></td>
<td align="right">1,149,236
</td></tr>
<tr>
<td align="right">16</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Indonesia" title="Indonesia">Indonesia</a></td>
<td align="right">1,015,411
</td></tr>
<tr>
<td align="right">17</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1200" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Turkey.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/35px-Flag_of_Turkey.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/45px-Flag_of_Turkey.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Turkey" title="Turkey">Turkey</a></td>
<td align="right">849,480
</td></tr>
<tr>
<td align="right">18</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Netherlands" title="Netherlands">Netherlands</a></td>
<td align="right">825,745
</td></tr>
<tr>
<td align="right">19</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Saudi_Arabia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/35px-Flag_of_Saudi_Arabia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/45px-Flag_of_Saudi_Arabia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia">Saudi Arabia</a></td>
<td align="right">683,827
</td></tr>
<tr>
<td align="right">20</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1000" height="16" src="./List of countries by GDP (nominal) - Wikipedia_files/16px-Flag_of_Switzerland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/24px-Flag_of_Switzerland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/32px-Flag_of_Switzerland.svg.png 2x" width="16"/>  </span><a href="https://en.wikipedia.org/wiki/Switzerland" title="Switzerland">Switzerland</a></td>
<td align="right">678,575
</td></tr>
<tr>
<td align="right">21</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="800" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Argentina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/35px-Flag_of_Argentina.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/46px-Flag_of_Argentina.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Argentina" title="Argentina">Argentina</a></td>
<td align="right">637,717
</td></tr>
<tr>
<td align="right">22</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Taiwan" title="Taiwan">Taiwan</a></td>
<td align="right">579,302
</td></tr>
<tr>
<td align="right">23</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1600" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Sweden.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/35px-Flag_of_Sweden.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/46px-Flag_of_Sweden.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Sweden" title="Sweden">Sweden</a></td>
<td align="right">538,575
</td></tr>
<tr>
<td align="right">24</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1280" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Poland.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/35px-Flag_of_Poland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/46px-Flag_of_Poland.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Poland" title="Poland">Poland</a></td>
<td align="right">524,886
</td></tr>
<tr>
<td align="right">25</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Belgium_(civil).svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/35px-Flag_of_Belgium_%28civil%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/45px-Flag_of_Belgium_%28civil%29.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Belgium" title="Belgium">Belgium</a></td>
<td align="right">494,733
</td></tr>
<tr>
<td align="right">26</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Thailand.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/35px-Flag_of_Thailand.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/45px-Flag_of_Thailand.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Thailand" title="Thailand">Thailand</a></td>
<td align="right">455,378
</td></tr>
<tr>
<td align="right">27</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="360" data-file-width="630" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/35px-Flag_of_Iran.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/46px-Flag_of_Iran.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Iran" title="Iran">Iran</a></td>
<td align="right">431,920
</td></tr>
<tr>
<td align="right">28</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Austria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/35px-Flag_of_Austria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/45px-Flag_of_Austria.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Austria" title="Austria">Austria</a></td>
<td align="right">416,845
</td></tr>
<tr>
<td align="right">29</td>

In [6]:
sources = data_table.tbody.findAll('tr', recursive=False)[0]
sources_list = [td for td in sources.findAll('td')]
print(len(sources_list))

3

In [53]:
data = data_table.tbody.findAll('tr', recursive=False)[1].findAll('td', recursive=False)
len(data)
print(data)

[<td>
<table class="wikitable sortable jquery-tablesorter" style="margin-left:auto; margin-right:auto; margin-top:0;">
<thead><tr>
<th class="headerSort" data-sort-type="number" role="columnheader button" style="width:2em;" tabindex="0" title="Sort ascending">Rank</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Country</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">GDP<br/>(US$MM)
</th></tr></thead><tbody>
<tr style="font-weight:bold;background:#eaecf0">
<td data-sort-value="-1"> </td>
<td data-sort-value=""><span class="flagicon" style="padding-left:25px;"> </span><i><a href="https://en.wikipedia.org/wiki/Gross_world_product" title="Gross world product">World</a></i><sup class="reference" id="cite_ref-IMF_Groups_19-1"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-IMF_Groups-19">[19]</a></sup></td>
<td align="right">79,865,481
</td></tr>
<tr>
<td align="right">1</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_States" title="United States">United States</a></td>
<td align="right">19,390,600
</td></tr>
<tr>
<td align="right">2</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_People's_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/China" title="China">China</a><sup class="reference" id="cite_ref-China-THM_23-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-China-THM-23">[n 1]</a></sup></td>
<td align="right">12,014,610
</td></tr>
<tr>
<td align="right">3</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/35px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/45px-Flag_of_Japan.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Japan" title="Japan">Japan</a></td>
<td align="right">4,872,135
</td></tr>
<tr>
<td align="right">4</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/35px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/46px-Flag_of_Germany.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Germany" title="Germany">Germany</a></td>
<td align="right">3,684,816
</td></tr>
<tr>
<td align="right">5</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_Kingdom" title="United Kingdom">United Kingdom</a></td>
<td align="right">2,624,529
</td></tr>
<tr>
<td align="right">6</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="900" data-file-width="1350" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/India" title="India">India</a></td>
<td align="right">2,611,012
</td></tr>
<tr>
<td align="right">7</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_France.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/35px-Flag_of_France.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/France" title="France">France</a></td>
<td align="right">2,583,560
</td></tr>
<tr>
<td align="right">8</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="504" data-file-width="720" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/22px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/33px-Flag_of_Brazil.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/43px-Flag_of_Brazil.svg.png 2x" width="22"/> </span><a href="https://en.wikipedia.org/wiki/Brazil" title="Brazil">Brazil</a></td>
<td align="right">2,054,969
</td></tr>
<tr>
<td align="right">9</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1500" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Italy.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/35px-Flag_of_Italy.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/45px-Flag_of_Italy.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Italy" title="Italy">Italy</a></td>
<td align="right">1,937,894
</td></tr>
<tr>
<td align="right">10</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="1000" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/Flag_of_Canada.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/35px-Flag_of_Canada.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/46px-Flag_of_Canada.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Canada" title="Canada">Canada</a></td>
<td align="right">1,652,412
</td></tr>
<tr>
<td align="right">11</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/South_Korea" title="South Korea">South Korea</a></td>
<td align="right">1,538,030
</td></tr>
<tr>
<td align="right">12</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/35px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/45px-Flag_of_Russia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Russia" title="Russia">Russia</a><sup class="reference" id="cite_ref-Russia_24-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-Russia-24">[n 2]</a></sup></td>
<td align="right">1,527,469
</td></tr>
<tr>
<td align="right">13</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="640" data-file-width="1280" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Australia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/35px-Flag_of_Australia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/46px-Flag_of_Australia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Australia" title="Australia">Australia</a></td>
<td align="right">1,379,548
</td></tr>
<tr>
<td align="right">14</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Spain.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/35px-Flag_of_Spain.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/45px-Flag_of_Spain.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Spain" title="Spain">Spain</a></td>
<td align="right">1,313,951
</td></tr>
<tr>
<td align="right">15</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="480" data-file-width="840" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/35px-Flag_of_Mexico.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/46px-Flag_of_Mexico.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Mexico" title="Mexico">Mexico</a></td>
<td align="right">1,149,236
</td></tr>
<tr>
<td align="right">16</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Indonesia" title="Indonesia">Indonesia</a></td>
<td align="right">1,015,411
</td></tr>
<tr>
<td align="right">17</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1200" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Turkey.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/35px-Flag_of_Turkey.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/45px-Flag_of_Turkey.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Turkey" title="Turkey">Turkey</a></td>
<td align="right">849,480
</td></tr>
<tr>
<td align="right">18</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Netherlands" title="Netherlands">Netherlands</a></td>
<td align="right">825,745
</td></tr>
<tr>
<td align="right">19</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Saudi_Arabia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/35px-Flag_of_Saudi_Arabia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/45px-Flag_of_Saudi_Arabia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia">Saudi Arabia</a></td>
<td align="right">683,827
</td></tr>
<tr>
<td align="right">20</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1000" height="16" src="./List of countries by GDP (nominal) - Wikipedia_files/16px-Flag_of_Switzerland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/24px-Flag_of_Switzerland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/32px-Flag_of_Switzerland.svg.png 2x" width="16"/>  </span><a href="https://en.wikipedia.org/wiki/Switzerland" title="Switzerland">Switzerland</a></td>
<td align="right">678,575
</td></tr>
<tr>
<td align="right">21</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="800" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Argentina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/35px-Flag_of_Argentina.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/46px-Flag_of_Argentina.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Argentina" title="Argentina">Argentina</a></td>
<td align="right">637,717
</td></tr>
<tr>
<td align="right">22</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Taiwan" title="Taiwan">Taiwan</a></td>
<td align="right">579,302
</td></tr>
<tr>
<td align="right">23</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1600" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Sweden.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/35px-Flag_of_Sweden.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/46px-Flag_of_Sweden.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Sweden" title="Sweden">Sweden</a></td>
<td align="right">538,575
</td></tr>
<tr>
<td align="right">24</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1280" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Poland.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/35px-Flag_of_Poland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/46px-Flag_of_Poland.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Poland" title="Poland">Poland</a></td>
<td align="right">524,886
</td></tr>
<tr>
<td align="right">25</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Belgium_(civil).svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/35px-Flag_of_Belgium_%28civil%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/45px-Flag_of_Belgium_%28civil%29.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Belgium" title="Belgium">Belgium</a></td>
<td align="right">494,733
</td></tr>
<tr>
<td align="right">26</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Thailand.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/35px-Flag_of_Thailand.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/45px-Flag_of_Thailand.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Thailand" title="Thailand">Thailand</a></td>
<td align="right">455,378
</td></tr>
<tr>
<td align="right">27</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="360" data-file-width="630" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/35px-Flag_of_Iran.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/46px-Flag_of_Iran.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Iran" title="Iran">Iran</a></td>
<td align="right">431,920
</td></tr>
<tr>
<td align="right">28</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Austria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/35px-Flag_of_Austria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/45px-Flag_of_Austria.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Austria" title="Austria">Austria</a></td>
<td align="right">416,845
</td></tr>
<tr>
<td align="right">29</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1100" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/21px-Flag_of_Norway.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/32px-Flag_of_Norway.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/41px-Flag_of_Norway.svg.png 2x" width="21"/> </span><a href="https://en.wikipedia.org/wiki/Norway" title="Norway">Norway</a></td>
<td align="right">396,457
</td></tr>
<tr>
<td align="right">30</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/Flag_of_the_United_Arab_Emirates.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/35px-Flag_of_the_United_Arab_Emirates.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/46px-Flag_of_the_United_Arab_Emirates.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_Arab_Emirates" title="United Arab Emirates">United Arab Emirates</a></td>
<td align="right">377,435
</td></tr>
<tr>
<td align="right">31</td>

In [8]:
data_tables = []
for td in data:
    data_tables.append(td.findAll('table'))

In [47]:
len(data_tables)
print(data_tables)

[[<table class="wikitable sortable jquery-tablesorter" style="margin-left:auto; margin-right:auto; margin-top:0;">
<thead><tr>
<th class="headerSort" data-sort-type="number" role="columnheader button" style="width:2em;" tabindex="0" title="Sort ascending">Rank</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">Country</th>
<th class="headerSort" role="columnheader button" tabindex="0" title="Sort ascending">GDP<br/>(US$MM)
</th></tr></thead><tbody>
<tr style="font-weight:bold;background:#eaecf0">
<td data-sort-value="-1"> </td>
<td data-sort-value=""><span class="flagicon" style="padding-left:25px;"> </span><i><a href="https://en.wikipedia.org/wiki/Gross_world_product" title="Gross world product">World</a></i><sup class="reference" id="cite_ref-IMF_Groups_19-1"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-IMF_Groups-19">[19]</a></sup></td>
<td align="right">79,865,481
</td></tr>
<tr>
<td align="right">1</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_States" title="United States">United States</a></td>
<td align="right">19,390,600
</td></tr>
<tr>
<td align="right">2</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_People's_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/China" title="China">China</a><sup class="reference" id="cite_ref-China-THM_23-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-China-THM-23">[n 1]</a></sup></td>
<td align="right">12,014,610
</td></tr>
<tr>
<td align="right">3</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Japan.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/35px-Flag_of_Japan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/45px-Flag_of_Japan.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Japan" title="Japan">Japan</a></td>
<td align="right">4,872,135
</td></tr>
<tr>
<td align="right">4</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/35px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/46px-Flag_of_Germany.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Germany" title="Germany">Germany</a></td>
<td align="right">3,684,816
</td></tr>
<tr>
<td align="right">5</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_United_Kingdom.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/35px-Flag_of_the_United_Kingdom.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/46px-Flag_of_the_United_Kingdom.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_Kingdom" title="United Kingdom">United Kingdom</a></td>
<td align="right">2,624,529
</td></tr>
<tr>
<td align="right">6</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="900" data-file-width="1350" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_India.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/35px-Flag_of_India.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/45px-Flag_of_India.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/India" title="India">India</a></td>
<td align="right">2,611,012
</td></tr>
<tr>
<td align="right">7</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_France.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/35px-Flag_of_France.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/45px-Flag_of_France.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/France" title="France">France</a></td>
<td align="right">2,583,560
</td></tr>
<tr>
<td align="right">8</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="504" data-file-width="720" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/22px-Flag_of_Brazil.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/33px-Flag_of_Brazil.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/43px-Flag_of_Brazil.svg.png 2x" width="22"/> </span><a href="https://en.wikipedia.org/wiki/Brazil" title="Brazil">Brazil</a></td>
<td align="right">2,054,969
</td></tr>
<tr>
<td align="right">9</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1500" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Italy.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/35px-Flag_of_Italy.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/45px-Flag_of_Italy.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Italy" title="Italy">Italy</a></td>
<td align="right">1,937,894
</td></tr>
<tr>
<td align="right">10</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="1000" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/Flag_of_Canada.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/35px-Flag_of_Canada.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/c/cf/Flag_of_Canada.svg/46px-Flag_of_Canada.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Canada" title="Canada">Canada</a></td>
<td align="right">1,652,412
</td></tr>
<tr>
<td align="right">11</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_South_Korea.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/35px-Flag_of_South_Korea.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/45px-Flag_of_South_Korea.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/South_Korea" title="South Korea">South Korea</a></td>
<td align="right">1,538,030
</td></tr>
<tr>
<td align="right">12</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Russia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/35px-Flag_of_Russia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/45px-Flag_of_Russia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Russia" title="Russia">Russia</a><sup class="reference" id="cite_ref-Russia_24-0"><a href="https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)#cite_note-Russia-24">[n 2]</a></sup></td>
<td align="right">1,527,469
</td></tr>
<tr>
<td align="right">13</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="640" data-file-width="1280" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Australia.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/35px-Flag_of_Australia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/46px-Flag_of_Australia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Australia" title="Australia">Australia</a></td>
<td align="right">1,379,548
</td></tr>
<tr>
<td align="right">14</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Spain.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/35px-Flag_of_Spain.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/45px-Flag_of_Spain.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Spain" title="Spain">Spain</a></td>
<td align="right">1,313,951
</td></tr>
<tr>
<td align="right">15</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="480" data-file-width="840" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Mexico.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/35px-Flag_of_Mexico.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/46px-Flag_of_Mexico.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Mexico" title="Mexico">Mexico</a></td>
<td align="right">1,149,236
</td></tr>
<tr>
<td align="right">16</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Indonesia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/35px-Flag_of_Indonesia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/45px-Flag_of_Indonesia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Indonesia" title="Indonesia">Indonesia</a></td>
<td align="right">1,015,411
</td></tr>
<tr>
<td align="right">17</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1200" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Turkey.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/35px-Flag_of_Turkey.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/45px-Flag_of_Turkey.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Turkey" title="Turkey">Turkey</a></td>
<td align="right">849,480
</td></tr>
<tr>
<td align="right">18</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Netherlands" title="Netherlands">Netherlands</a></td>
<td align="right">825,745
</td></tr>
<tr>
<td align="right">19</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="750" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Saudi_Arabia.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/35px-Flag_of_Saudi_Arabia.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/45px-Flag_of_Saudi_Arabia.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Saudi_Arabia" title="Saudi Arabia">Saudi Arabia</a></td>
<td align="right">683,827
</td></tr>
<tr>
<td align="right">20</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1000" height="16" src="./List of countries by GDP (nominal) - Wikipedia_files/16px-Flag_of_Switzerland.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/24px-Flag_of_Switzerland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/32px-Flag_of_Switzerland.svg.png 2x" width="16"/>  </span><a href="https://en.wikipedia.org/wiki/Switzerland" title="Switzerland">Switzerland</a></td>
<td align="right">678,575
</td></tr>
<tr>
<td align="right">21</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="500" data-file-width="800" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Argentina.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/35px-Flag_of_Argentina.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/46px-Flag_of_Argentina.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Argentina" title="Argentina">Argentina</a></td>
<td align="right">637,717
</td></tr>
<tr>
<td align="right">22</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_the_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/35px-Flag_of_the_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/45px-Flag_of_the_Republic_of_China.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Taiwan" title="Taiwan">Taiwan</a></td>
<td align="right">579,302
</td></tr>
<tr>
<td align="right">23</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="1000" data-file-width="1600" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Sweden.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/35px-Flag_of_Sweden.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/46px-Flag_of_Sweden.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Sweden" title="Sweden">Sweden</a></td>
<td align="right">538,575
</td></tr>
<tr>
<td align="right">24</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1280" height="14" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Poland.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/35px-Flag_of_Poland.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/46px-Flag_of_Poland.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Poland" title="Poland">Poland</a></td>
<td align="right">524,886
</td></tr>
<tr>
<td align="right">25</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="300" data-file-width="450" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Belgium_(civil).svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/35px-Flag_of_Belgium_%28civil%29.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/45px-Flag_of_Belgium_%28civil%29.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Belgium" title="Belgium">Belgium</a></td>
<td align="right">494,733
</td></tr>
<tr>
<td align="right">26</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Thailand.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/35px-Flag_of_Thailand.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/45px-Flag_of_Thailand.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Thailand" title="Thailand">Thailand</a></td>
<td align="right">455,378
</td></tr>
<tr>
<td align="right">27</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="360" data-file-width="630" height="13" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Iran.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/35px-Flag_of_Iran.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/46px-Flag_of_Iran.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Iran" title="Iran">Iran</a></td>
<td align="right">431,920
</td></tr>
<tr>
<td align="right">28</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/23px-Flag_of_Austria.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/35px-Flag_of_Austria.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/45px-Flag_of_Austria.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/Austria" title="Austria">Austria</a></td>
<td align="right">416,845
</td></tr>
<tr>
<td align="right">29</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="800" data-file-width="1100" height="15" src="./List of countries by GDP (nominal) - Wikipedia_files/21px-Flag_of_Norway.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/32px-Flag_of_Norway.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/41px-Flag_of_Norway.svg.png 2x" width="21"/> </span><a href="https://en.wikipedia.org/wiki/Norway" title="Norway">Norway</a></td>
<td align="right">396,457
</td></tr>
<tr>
<td align="right">30</td>
<td><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1200" height="12" src="./List of countries by GDP (nominal) - Wikipedia_files/Flag_of_the_United_Arab_Emirates.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/35px-Flag_of_the_United_Arab_Emirates.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/46px-Flag_of_the_United_Arab_Emirates.svg.png 2x" width="23"/> </span><a href="https://en.wikipedia.org/wiki/United_Arab_Emirates" title="United Arab Emirates">United Arab Emirates</a></td>
<td align="right">377,435
</td></tr>
<tr>
<td align="right">31</td>

In [10]:
source_names = [source.findAll('a')[0].getText() for source in sources_list]
print(source_names)

['International Monetary Fund', 'World Bank', 'United Nations']

In [11]:
header1 = [th.getText().strip() for th in data_tables[0][0].findAll('thead')[0].findAll('th')]
header1

['Rank', 'Country', 'GDP(US$MM)']

In [12]:
rows1 = data_tables[0][0].findAll('tbody')[0].findAll('tr')

In [13]:
data_rows1 = [[td.get_text().strip() for td in tr.findAll('td')] for tr in rows1]

In [14]:
df1 = pd.DataFrame(data_rows1, columns=header1)
df1.head()

  Rank        Country  GDP(US$MM)
0           World[19]  79,865,481
1    1  United States  19,390,600
2    2     China[n 1]  12,014,610
3    3          Japan   4,872,135
4    4        Germany   3,684,816

In [15]:
header2 = [th.getText().strip() for th in data_tables[1][0].findAll('thead')[0].findAll('th')]
header2

['Rank', 'Country', 'GDP(US$MM)']

In [16]:
rows2 = data_tables[1][0].findAll('tbody')[0].findAll('tr')

In [17]:
def find_right_text(i, td):
    if i == 0:
        return td.getText().strip()
    elif i == 1:
        return td.getText().strip()
    else:
        index = td.text.find("♠")
        return td.text[index+1:].strip()

In [18]:
data_rows2 = [[find_right_text(i, td) for i, td in enumerate(tr.findAll('td'))] for tr in rows2]

In [19]:
df2 = pd.DataFrame(data_rows2, columns=header2)
df2.head()

  Rank             Country  GDP(US$MM)
0                    World  80,683,787
1    1       United States  19,390,604
2       European Union[23]  17,277,698
3    2          China[n 4]  12,237,700
4    3               Japan   4,872,137

In [20]:
header3 = [th.getText().strip() for th in data_tables[2][0].findAll('thead')[0].findAll('th')]
header3

['Rank', 'Country', 'GDP(US$MM)']

In [21]:
rows3 = data_tables[2][0].findAll('tbody')[0].findAll('tr')

In [22]:
data_rows3 = [[find_right_text(i, td) for i, td in enumerate(tr.findAll('td'))] for tr in rows2]

In [23]:
df3 = pd.DataFrame(data_rows3, columns=header3)
df3.head()

  Rank             Country  GDP(US$MM)
0                    World  80,683,787
1    1       United States  19,390,604
2       European Union[23]  17,277,698
3    2          China[n 4]  12,237,700
4    3               Japan   4,872,137